version: "3"

services:
  onacut_backend_dev:
    container_name: onacut_backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    tty: true
    ports:
      - "5000:5000"
    command: python server.py
    env_file:
      - ./backend/.env

  onacut_frontend_dev:
    container_name: onacut_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env